format = """
[┌───────────────────](bold green)
[│](bold green)$kubernetes$aws$hostname$directory$nodejs$rust$java$golang$git_branch$git_state$git_status$time
[└─>](bold green)"""

scan_timeout = 10
command_timeout = 300
add_newline = false

[kubernetes]
format = "[$symbol$context](green) "
disabled = true

[aws]
format = "[$symbol$profile](green) "
disabled = true

[hostname]
format = "[$hostname]($style) "
ssh_only = true

[directory]
truncation_length = 100
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style)"

[git_status]
# WSL環境でgit statusは重いため軽量化
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = ""
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = ""
deleted = ""

[nodejs]
format = "[$symbol($version )]($style)"
detect_files = ["package.json"]
detect_folders = []

[rust]
format = "[$symbol($version )]($style)"
detect_files = ["Cargo.toml"]
detect_folders = []

[java]
format = "[$symbol($version )]($style)"
detect_files = [".java-version"]
detect_folders = []

[golang]
format = "[$symbol($version )]($style)"
detect_files = ["go.mod"]
detect_folders = []
