apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:4DbUHeImTxqox1ny8WRAaSo=,iv:kID2v/EnoEtBO0mIdQWHOXytRATlCX6bg6OkJJ/Gai8=,tag:RjjRCD00WqVYAvqn+U6jcQ==,type:str]
    client_secret: ENC[AES256_GCM,data:o9pcK+OHZrRrqx/eWxLNOmWwaYg5D6u9vavwXBDOE4KmU0w22YV1H1aX9drLFh2wvnI/SwMqgvRY42oaj7C9aQ==,iv:a4J8qWoROkaRwzexDGGITTBo6Sa0w25fBChVtq0eqiM=,tag:YzRCU2V9cCzLPzckYir1aA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDL1FRb2FNbXJ1K202KzIv
            VEpBVmpCaXBvMXRQTW5vK042OWVVZGVOR0Y0ClY1Nm81aDRqNWFHWFJROEpVVWpB
            Q0F3b0h2Q2Jwd25ycXhvb3hxNWJGVTgKLS0tIDR6Z01KN05xblFNZlpTWkwxV29V
            L044U3RXeCt1MU1wb2s3c1FVSndicjQKQ1QFVbr8zbeN/aY6RB7hh9vitRS548Fb
            bI7WCNdsayqxedfqTN/HV/LK2Bnhqm4TVSGEayikw3cde5XXRjP8SA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cnhna00dmmq9fpeg4swj2ckk4dujggcgn7pxk4lps68heefc2ffsf7qhat
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T04:54:54Z"
    mac: ENC[AES256_GCM,data:iSNaut4zhJbHaIkZsPmXGDZJlowbl/nQDiMLWeDQilysPwfqeUZL0+aicZ3+eGT5+mAkH7X78FyI7omn6Qtc4VdkILaVCt8e/Z1n+Pcq6jUlsy8Rnmr/NxKljX+BOnIACshfVVlGWWSBaOOqt3r4CAi1VV9YigNb1LFEOqL2kCA=,iv:5beyRhWU9RDzliuKh6pNu5yXM0ovPu3kFjDiwSSRJws=,tag:T2eWWIkgMZ5emFPo0WVfbQ==,type:str]
    version: 3.13.1
