apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Flux bootstrap がこの二つを実マニフェストへ置き換える。
  - gotk-components.yaml
  - gotk-sync.yaml
  - infrastructure.yaml
  - jellyfin.yaml
