apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      version: "1.102.3"
  values:
    # chart が Tailscale CRD を管理する。Ingress を処理する前に作成される。
    installCRDs: true
