return {
  {
    "nvim-treesitter/nvim-treesitter", 
    build = ":TSUpdate", 
    main = 'nvim-treesitter.configs', 
    opts = function(_, opts)
      opts.highlight = { enable = true }
      opts.ensure_installed = {
        "bash",
        "c",
        "css",
        "csv",
        "dart",
        "diff",
        "editorconfig",
        "fish",
        "git_config",
        "git_rebase",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "helm",
        "html",
        "java",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        "just",
        "lua",
        "make",
        "markdown",
        "nix",
        "proto",
        "regex",
        "rust",
        "sql",
        "tmux",
        "toml",
        "tsv",
        "tsx",
        "typescript",
        "vim",
        "yaml"
      }
    end,
  },
  {
    "nvim-treesitter/nvim-treesitter-textobjects",
    event = "CursorMoved",
  },
}