name: Darwin CI
on:
  push:
    branches: [main]
    paths:
      - 'darwin/**'
      - 'modules/**'
      - 'nixvim/**'
      - '.github/workflows/darwin.yml'
      - '.github/actions/setup-nix/**'
      - 'Makefile'
      - 'vscode/**'
      - 'scripts/**'
  pull_request:
    branches: [main]
    paths:
      - 'darwin/**'
      - 'modules/**'
      - 'nixvim/**'
      - '.github/workflows/darwin.yml'
      - '.github/actions/setup-nix/**'
      - 'Makefile'
      - 'vscode/**'
      - 'scripts/**'

jobs:
  build:
    runs-on: macos-latest
    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - uses: actions/checkout@v6

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          configure-global-nixconf: "true"
          add-channel: "false"

      - name: Build CI home-manager activation package
        timeout-minutes: 45
        shell: zsh {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIXVIM_CONFIG_INPUT: path:${{ github.workspace }}/nixvim
          DOTFILES_SHARED_INPUT: path:${{ github.workspace }}/modules
        run: |
          export USER=runner
          source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          cd darwin
          nix build path:.#homeConfigurations.ci.activationPackage --impure --no-write-lock-file --override-input nixvim-config "$NIXVIM_CONFIG_INPUT" --override-input dotfiles-shared "$DOTFILES_SHARED_INPUT"

      - name: Check nix-darwin configuration
        timeout-minutes: 60
        shell: zsh {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
          USER: runner
          NIXVIM_CONFIG_INPUT: path:${{ github.workspace }}/nixvim
          DOTFILES_SHARED_INPUT: path:${{ github.workspace }}/modules
        run: |
          source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          export NIX_CONFIG="access-tokens = github.com=$GITHUB_TOKEN"
          cd darwin
          nix --extra-experimental-features "nix-command flakes" build path:.#darwinConfigurations.all.system --impure --no-write-lock-file --override-input nixvim-config "$NIXVIM_CONFIG_INPUT" --override-input dotfiles-shared "$DOTFILES_SHARED_INPUT"

      - name: Check nixvim configuration
        timeout-minutes: 30
        shell: zsh {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          export NIX_CONFIG="access-tokens = github.com=$GITHUB_TOKEN"
          cd nixvim
          nix build .#packages.aarch64-darwin.default --impure --no-write-lock-file
