name: Dotfiles CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: MacOS Setting
        run: |
          bash ./just-install.sh
          just nix-install
          just nix-darwin-install
          just nix-apply
          just nix-darwin-apply
          make all
