name: Dotfiles CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache just-install
        uses: actions/cache@v3
        with:
          path: ~/.cache/just-install
          key: ${{ runner.os }}-just-install-${{ hashFiles('just-install.sh') }}
          restore-keys: |
            ${{ runner.os }}-just-install-
      - name: MacOS Setting
        run: |
          make deploy
          bash ./just-install.sh
          export USER=miyoshi_s
          export DARWIN_USER=runner
          just nix-install
          echo $HOME
          just nix-apply
          just nix-darwin-install
          just nix-darwin-apply
          make vim
