name: Dotfiles CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: MacOS Setting
        run: |
          make deploy
          make nix-install
          make nix-darwin-install
          make nix-apply
          make nix-darwin-apply
          make vim
