name: Dotfiles CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache installed tools
        uses: extractions/setup-just@v1
        uses: actions/cache@v3
        with:
          path: $HOME/.local/bin
          key: ${{ runner.os }}-installed-tools-${{ hashFiles('just-install.sh') }}
          restore-keys: |
            ${{ runner.os }}-installed-tools-
      - name: MacOS Setting
        shell: zsh {0}
        run: |
          just list-deploy-targets
          just deploy
          just nix-install
          export USER=runner
          just nix-apply
          just nix-darwin-install
          just nix-darwin-apply
          just set-up-vim
          zsh
          ls -al $HOME
          just nix-update-all