name: Dotfiles CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org/
      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check flakes
        uses: DeterminateSystems/flake-checker-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Localnix.conf
        shell: zsh {0}
        run : |
          if [ ! -d "$HOME/.config/nix" ]; then
            mkdir -p "$HOME/.config/nix"
          fi
          echo 'experimental-features = nix-command flakes' > "$HOME/.config/nix/nix.conf"
          echo 'warn-dirty = false' >> "$HOME/.config/nix/nix.conf"
      - name: Prepare Nix
        shell: zsh {0}
        run: |
          echo "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}" >> $HOME/.config/nix/nix.conf
          source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          nix-channel --add https://nixos.org/channels/nixpkgs-unstable
          nix-channel --update
      - name: Set global nix.conf
        shell: zsh {0}
        run: |
          sudo mkdir -p /etc/nix
          if [ -f /etc/nix/nix.conf ]; then
            sudo mv /etc/nix/nix.conf /etc/nix/nix.conf.before-nix-darwin
          fi
          echo 'use-xdg-base-directories = true' | sudo tee /etc/nix/nix.conf
          echo 'extra-trusted-users = runner' | sudo tee -a /etc/nix/nix.conf
          echo "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}" | sudo tee -a /etc/nix/nix.conf
      - name: Apply home-manager
        shell: zsh {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export USER=runner
          source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          nix flake update
          nix run nixpkgs#home-manager -- switch --flake .#home --impure
      - name: Apply nix-darwin
        shell: zsh {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f /etc/nix/nix.conf ]; then
            sudo mv /etc/nix/nix.conf /etc/nix/nix.conf.before-nix-darwin
          fi
          # backup /etc/hosts
          if [ -f /etc/hosts ]; then
            sudo mv /etc/hosts /etc/hosts.before-nix-darwin
          fi
          source $HOME/.zshenv
          source $HOME/.config/zsh/.zshrc
          just nix-darwin-apply
      - name: Run nix-update-all
        shell: zsh {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source $HOME/.zshenv
          source $HOME/.config/zsh/.zshrc
          just nix-update-all
      - name: Run vscode-settings
        shell: zsh {0}
        run: |
          source $HOME/.zshenv
          source $HOME/.config/zsh/.zshrc
          just vscode-apply
          just vscode-save
