name: Dotfiles CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      id-token: "write"
      contents: "read"
    env:
      NIXPKGS_GITHUB_TOKEN: ${{ secrets.PAT_FOR_DOT_FILES }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Just
        uses: extractions/setup-just@v1
      # - name: Install Nix
      #   uses: DeterminateSystems/nix-installer-action@main
      # - name: Nix cache
      #   uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check flakes
        uses: DeterminateSystems/flake-checker-action@main
      - name: MacOS Setting
        shell: zsh {0}
        run: |
          just list-deploy-targets
          just deploy
          just nix-install
          export USER=runner
          just nix-apply
          just nix-darwin-install
          just nix-darwin-apply
          just set-up-vim
          zsh
          ls -al $HOME
          just nix-update-all
          just nix-uninstall
