name: Dotfiles CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: MacOS Setting
        run: |
          MAS_APPS="$(cat Brewfile | grep -v brew | grep mas | sed 's/^.*"\(.*\)".*$/\1/' | tr '\n' ' ')"
          export HOMEBREW_BUNDLE_MAS_SKIP="$MAS_APPS"
          make all
