name: Dotfiles CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup Just
        uses: extractions/setup-just@v1
      - name: MacOS Setting
        shell: zsh {0}
        run: |
          just list-deploy-targets
          just deploy
          just nix-install
          export USER=runner
          just nix-apply
          just nix-darwin-install
          just nix-darwin-apply
          just set-up-vim
          zsh
          ls -al $HOME
          just nix-update-all
          just nix-uninstall
