name: Dotfiles CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: MacOS Setting
        run: |
          make deploy
          bash ./just-install.sh
          export USER=miyoshi_s
          export HOME=/Users/miyoshi_s
          just nix-install
          just nix-apply
          just nix-darwin-install
          just nix-darwin-apply
          make vim
