name: Dotfiles CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check flakes
        uses: DeterminateSystems/flake-checker-action@main
      - name: Set nix.conf
        shell: zsh {0}
        run : |
          if [ ! -d "$HOME/.config" ]; then
            mkdir -p "$HOME/.config"
          fi
          if [ ! -f "$HOME/.config/nix.conf" ]; then
            echo 'experimental-features = nix-command flakes' > "$HOME/.config/nix.conf"
          fi
      - name: Prepare Nix
        shell: zsh {0}
        run: |
          echo "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}" >> $HOME/.config/nix.conf
            source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
            nix-channel --add https://nixos.org/channels/nixpkgs-unstable
            nix-channel --update
      - name: Apply home-manager
        shell: zsh {0}
        run: |
          export USER=runner
          echo $USER
          source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          nix flake update
          nix run nixpkgs#home-manager -- switch --flake .#home --impure
          just
      - name: Crear initial nix.conf
        run: |
          sudo rm /etc/nix/nix.conf # FIXME: work around
      - name: Apply nix-darwin
        shell: zsh {0}
        run: |
          source $HOME/.zshrc
          just nix-darwin-apply
      - name: Run nix-update-all
        shell: zsh {0}
        run: |
          source $HOME/.zshrc
          just nix-update-all
      - name: Run npm-tools
        shell: zsh {0}
        run: |
          source $HOME/.zshrc
          echo $PATH | grep -q /opt/homebrew/bin || export PATH="/opt/homebrew/bin:$PATH"
          just npm-tools
      - name: Run vscode-settings
        shell: zsh {0}
        run: |
          source $HOME/.zshrc
          just vscode-apply
          just vscode-save
