name: Dotfiles CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - uses: actions/checkout@v3
      - name: Setup Just
        uses: extractions/setup-just@v1
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check flakes
        uses: DeterminateSystems/flake-checker-action@main
      - name: MacOS Setting
        shell: zsh {0}
        run: |
          just list-deploy-targets
          just deploy
          echo "access-tokens = github.com=${{ secrets.PERSONAL_ACCESS_TOKEN }}" >> $HOME/.config/nix/nix.conf
          # just nix-install
          just nix-channel-update
          export USER=runner
          just nix-apply
          just nix-darwin-install
          just nix-darwin-apply
          just set-up-vim
          zsh
          ls -al $HOME
          just nix-update-all
